language: rust

rust:
    - nightly

matrix:
    include:
        - os: linux
          dist: xenial
          sudo: required

addons:
    apt:
        packages:
            - libgstreamer1.0-dev
            - libgstrtspserver-1.0-dev
            - libcairo2-dev
            - libgtk-3-dev
            - gstreamer1.0-plugins-base
            - gstreamer1.0-plugins-good
            - gstreamer1.0-plugins-ugly
            - gstreamer1.0-plugins-bad
            - gstreamer1.0-tools
            - gstreamer1.0-libav
            - gstreamer1.0-plugins-bad-faad
            - gstreamer1.0-x
            - libx264-dev
            - librtmp-dev
            - libcurl4-gnutls-dev

script:
    - export GST_PLUGIN_PATH=`pwd`/target/debug
    - RUST_BACKTRACE=1 cargo test --verbose --no-fail-fast --all